language: java
services:
- docker
before_script:
- echo "starting travis build"
script:
- cd scripts
- sh build-service-jar.sh
after_script:
- echo "travis script finished"
after_success:
- echo "travis build was successful"
after_failure:
- echo "travis build was failed"